# Generated by Django 5.2.8 on 2025-11-17 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0, message='Rating cannot be less than 0.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be greater than 5.')]),
        ),
    ]
